development:
  adapter: mysql2
  database: db_development
  host: 127.0.0.1
  username: root
  password: root
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  database: db_test
  host: 127.0.0.1
  username: root
  password: root
  socket: /tmp/mysql.socket

production:
  adapter: mysql2
  database: db_production
  host: 127.0.0.1
  username: root
  password: root
  socket: /tmp/mysql.socket

